# Generated by Django 5.2.17 on 2026-08-29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("tenancy", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="MonitoredProduct",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("legacy_product_id", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("exact_model", models.CharField(blank=True, max_length=255)),
                ("variant", models.CharField(blank=True, max_length=255)),
                ("target_price_cents", models.PositiveBigIntegerField(blank=True, null=True)),
                ("preferred_payment_method", models.CharField(choices=[("PIX", "Pix"), ("CARD", "Cartao"), ("BOLETO", "Boleto")], default="PIX", max_length=16)),
                ("status", models.CharField(choices=[("ACTIVE", "Ativo"), ("PAUSED", "Pausado"), ("ARCHIVED", "Arquivado")], default="ACTIVE", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenancy.tenant")),
            ],
            options={
                "ordering": ("name", "id"),
                "constraints": [models.UniqueConstraint(condition=models.Q(("legacy_product_id", ""), _negated=True), fields=("tenant", "legacy_product_id"), name="product_tenant_legacy_id_unique")],
            },
        ),
        migrations.CreateModel(
            name="MonitoringRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("RUNNING", "Em execucao"), ("SUCCESS", "Sucesso"), ("FAILED", "Falha")], max_length=16)),
                ("mode", models.CharField(max_length=40)),
                ("input_file_name", models.CharField(max_length=255)),
                ("products_count", models.PositiveIntegerField(default=0)),
                ("links_count", models.PositiveIntegerField(default=0)),
                ("observations_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenancy.tenant")),
            ],
            options={
                "ordering": ("-started_at", "-id"),
                "constraints": [models.UniqueConstraint(condition=models.Q(("legacy_id__isnull", False)), fields=("tenant", "legacy_id"), name="run_tenant_legacy_id_unique")],
            },
        ),
        migrations.CreateModel(
            name="OfferSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("store", models.CharField(max_length=80)),
                ("url", models.URLField(max_length=2048)),
                ("expected_seller", models.CharField(blank=True, max_length=255)),
                ("expected_variant", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sources", to="monitoring.monitoredproduct")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenancy.tenant")),
            ],
            options={
                "ordering": ("store", "url"),
                "constraints": [models.UniqueConstraint(fields=("tenant", "product", "url"), name="source_tenant_product_url_unique")],
            },
        ),
        migrations.CreateModel(
            name="CollectorError",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField()),
                ("context", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="collector_errors", to="monitoring.monitoringrun")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenancy.tenant")),
            ],
            options={
                "ordering": ("occurred_at", "id"),
                "constraints": [models.UniqueConstraint(condition=models.Q(("legacy_id__isnull", False)), fields=("tenant", "legacy_id"), name="collector_error_tenant_legacy_id_unique")],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("attempted_at", models.DateTimeField()),
                ("channel", models.CharField(max_length=40)),
                ("event_type", models.CharField(max_length=80)),
                ("price_cents", models.BigIntegerField()),
                ("previous_price_cents", models.BigIntegerField()),
                ("status", models.CharField(max_length=16)),
                ("error_message", models.TextField(blank=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_deliveries", to="monitoring.monitoredproduct")),
                ("run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notification_deliveries", to="monitoring.monitoringrun")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenancy.tenant")),
            ],
            options={
                "ordering": ("attempted_at", "id"),
                "constraints": [models.UniqueConstraint(condition=models.Q(("legacy_id__isnull", False)), fields=("tenant", "legacy_id"), name="delivery_tenant_legacy_id_unique")],
            },
        ),
        migrations.CreateModel(
            name="PriceObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("observed_at", models.DateTimeField()),
                ("seller", models.CharField(max_length=255)),
                ("payment_method", models.CharField(max_length=40)),
                ("product_price_cents", models.BigIntegerField(blank=True, null=True)),
                ("shipping_price_cents", models.BigIntegerField(blank=True, null=True)),
                ("total_price_cents", models.BigIntegerField(blank=True, null=True)),
                ("delivery_min_days", models.IntegerField(blank=True, null=True)),
                ("delivery_max_days", models.IntegerField(blank=True, null=True)),
                ("in_stock", models.BooleanField()),
                ("status", models.CharField(max_length=40)),
                ("parser_version", models.CharField(max_length=80)),
                ("error_message", models.TextField(blank=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="observations", to="monitoring.monitoredproduct")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="observations", to="monitoring.monitoringrun")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="observations", to="monitoring.offersource")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenancy.tenant")),
            ],
            options={
                "ordering": ("observed_at", "id"),
                "indexes": [models.Index(fields=["tenant", "product", "observed_at"], name="monitoring__tenant__2d5223_idx")],
                "constraints": [models.UniqueConstraint(condition=models.Q(("legacy_id__isnull", False)), fields=("tenant", "legacy_id"), name="observation_tenant_legacy_id_unique")],
            },
        ),
        migrations.CreateModel(
            name="LegacyImportBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_file_name", models.CharField(max_length=255)),
                ("source_sha256", models.CharField(max_length=64)),
                ("source_counts", models.JSONField(default=dict)),
                ("imported_counts", models.JSONField(default=dict)),
                ("alert_cursor_at", models.DateTimeField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tenancy.tenant")),
            ],
            options={
                "ordering": ("-imported_at",),
                "constraints": [models.UniqueConstraint(fields=("tenant", "source_sha256"), name="legacy_batch_tenant_hash_unique")],
            },
        ),
    ]
