# Generated by Django 5.2.17 on 2026-08-29 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLinkPreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_url', models.URLField(max_length=2048)),
                ('canonical_url', models.URLField(max_length=2048)),
                ('store', models.CharField(choices=[('Amazon', 'Amazon Brasil'), ('KaBuM', 'KaBuM')], max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Consultando'), ('READY', 'Aguardando confirmacao'), ('FAILED', 'Falha na previa'), ('CONFIRMED', 'Confirmado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=16)),
                ('extracted_title', models.CharField(blank=True, max_length=500)),
                ('extracted_seller', models.CharField(blank=True, max_length=255)),
                ('extracted_price_cents', models.PositiveBigIntegerField(blank=True, null=True)),
                ('extracted_in_stock', models.BooleanField(blank=True, null=True)),
                ('supports_pix', models.BooleanField(default=False)),
                ('parser_version', models.CharField(blank=True, max_length=80)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='offersource',
            name='store',
            field=models.CharField(choices=[('Amazon', 'Amazon Brasil'), ('KaBuM', 'KaBuM')], max_length=80),
        ),
        migrations.AddConstraint(
            model_name='offersource',
            constraint=models.UniqueConstraint(fields=('tenant', 'url'), name='source_tenant_url_unique'),
        ),
        migrations.AddField(
            model_name='productlinkpreview',
            name='confirmed_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmation_preview', to='monitoring.offersource'),
        ),
        migrations.AddField(
            model_name='productlinkpreview',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_link_previews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productlinkpreview',
            name='target_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_previews', to='monitoring.monitoredproduct'),
        ),
        migrations.AddField(
            model_name='productlinkpreview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='productlinkpreview',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='monitoring__tenant__972214_idx'),
        ),
        migrations.AddIndex(
            model_name='productlinkpreview',
            index=models.Index(fields=['expires_at'], name='monitoring__expires_78b2dd_idx'),
        ),
    ]
