# Generated by Django 5.2.17 on 2026-08-29 15:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_productlinkpreview_alter_offersource_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Em execucao'), ('SUCCESS', 'Sucesso'), ('PARTIAL', 'Parcial'), ('FAILED', 'Falha')], default='RUNNING', max_length=16)),
                ('urls_planned', models.PositiveIntegerField(default=0)),
                ('urls_fetched', models.PositiveIntegerField(default=0)),
                ('sources_processed', models.PositiveIntegerField(default=0)),
                ('tenant_runs_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SharedOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store', models.CharField(choices=[('Amazon', 'Amazon Brasil'), ('KaBuM', 'KaBuM')], max_length=80)),
                ('canonical_url', models.URLField(max_length=2048, unique=True)),
                ('last_collected_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('store', 'canonical_url'),
            },
        ),
        migrations.AddField(
            model_name='monitoredproduct',
            name='baseline_observed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoredproduct',
            name='baseline_total_cents',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priceobservation',
            name='is_baseline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoringrun',
            name='collection_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_runs', to='monitoring.collectionbatch'),
        ),
        migrations.AddField(
            model_name='offersource',
            name='shared_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_sources', to='monitoring.sharedoffer'),
        ),
        migrations.CreateModel(
            name='SharedOfferObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('seller', models.CharField(blank=True, max_length=255)),
                ('product_price_cents', models.PositiveBigIntegerField(blank=True, null=True)),
                ('in_stock', models.BooleanField(default=False)),
                ('supports_pix', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=40)),
                ('parser_version', models.CharField(blank=True, max_length=80)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_observations', to='monitoring.collectionbatch')),
                ('shared_offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='monitoring.sharedoffer')),
            ],
            options={
                'ordering': ('observed_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='priceobservation',
            name='shared_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_observations', to='monitoring.sharedofferobservation'),
        ),
        migrations.AddIndex(
            model_name='sharedofferobservation',
            index=models.Index(fields=['shared_offer', 'observed_at'], name='monitoring__shared__4d15c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='sharedofferobservation',
            constraint=models.UniqueConstraint(fields=('batch', 'shared_offer'), name='base_observation_batch_offer_unique'),
        ),
    ]
