# Generated by Django 5.2.17 on 2026-08-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_collectionbatch_sharedoffer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedofferobservation',
            name='price_payment_method',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
