# Generated by Django 5.2.17 on 2026-08-29 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_sharedofferobservation_price_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionWorkerLease",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("owner", models.CharField(blank=True, max_length=128)),
                ("acquired_at", models.DateTimeField(blank=True, null=True)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CollectionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("DAILY_COLLECTION", "Coleta diaria")],
                        default="DAILY_COLLECTION",
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Na fila"),
                            ("RUNNING", "Em execucao"),
                            ("RETRY_WAIT", "Aguardando nova tentativa"),
                            ("SUCCESS", "Sucesso"),
                            ("DEAD", "Esgotado"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("available_at", models.DateTimeField()),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=4)),
                ("claimed_by", models.CharField(blank=True, max_length=128)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveBigIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                ("last_error_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="monitoring.collectionbatch",
                    ),
                ),
            ],
            options={
                "ordering": ("scheduled_for", "created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CollectionJobAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("worker_id", models.CharField(max_length=128)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Em execucao"),
                            ("SUCCESS", "Sucesso"),
                            ("FAILED", "Falha"),
                            ("ABANDONED", "Worker interrompido"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("duration_ms", models.PositiveBigIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                (
                    "collection_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_attempts",
                        to="monitoring.collectionbatch",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="monitoring.collectionjob",
                    ),
                ),
            ],
            options={
                "ordering": ("job", "number"),
            },
        ),
        migrations.AddIndex(
            model_name="collectionjob",
            index=models.Index(
                fields=["status", "available_at"],
                name="monitoring__status_c5d388_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionjob",
            index=models.Index(
                fields=["job_type", "scheduled_for"],
                name="monitoring__job_typ_7f8438_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionjobattempt",
            constraint=models.UniqueConstraint(
                fields=("job", "number"),
                name="collection_job_attempt_number_unique",
            ),
        ),
    ]
