# Generated by Django 5.2.17 on 2026-08-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0005_collectionworkerlease_collectionjob_and_more"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("CREATED", "Criado")],
                        default="CREATED",
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("occurred_at", models.DateTimeField()),
                ("current_price_cents", models.PositiveBigIntegerField()),
                ("previous_price_cents", models.PositiveBigIntegerField(blank=True, null=True)),
                ("historical_low_cents", models.PositiveBigIntegerField(blank=True, null=True)),
                ("target_price_cents", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "variation_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_events",
                        to="monitoring.priceobservation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_events",
                        to="monitoring.monitoredproduct",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["tenant", "product", "occurred_at"],
                        name="monitoring__tenant__103515_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status", "created_at"],
                        name="monitoring__tenant__d849cb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_price_drop_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default="1.00",
                        max_digits=5,
                    ),
                ),
                ("alert_new_historical_low", models.BooleanField(default=True)),
                ("alert_target_reached", models.BooleanField(default=True)),
                ("alert_back_in_stock", models.BooleanField(default=True)),
                ("alert_price_increase", models.BooleanField(default=False)),
                ("cooldown_minutes", models.PositiveIntegerField(default=360)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="monitoring.monitoredproduct",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("tenant_id", "product_id"),
                "indexes": [
                    models.Index(
                        fields=["tenant", "enabled"],
                        name="monitoring__tenant__b789cf_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "product"),
                        name="alert_rule_tenant_product_unique",
                    )
                ],
            },
        ),
    ]
