# Generated by Django 5.2.17 on 2026-08-29 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alertevent_alertrule'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='alert_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='monitoring.alertevent'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='delivery_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionjob',
            name='job_type',
            field=models.CharField(choices=[('DAILY_COLLECTION', 'Coleta diaria'), ('MANUAL_COLLECTION', 'Coleta manual')], default='DAILY_COLLECTION', max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='event_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='previous_price_cents',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['tenant', 'status', 'attempted_at'], name='monitoring__tenant__b8275c_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('alert_event__isnull', False)), fields=('alert_event', 'channel'), name='delivery_alert_event_channel_unique'),
        ),
    ]
