# Generated by Django 5.2.17 on 2026-09-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0007_notificationdelivery_alert_event_and_more"),
        ("tenancy", "0002_betaaccessgrant"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="offersource",
            name="source_tenant_url_unique",
        ),
        migrations.AddConstraint(
            model_name="offersource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("tenant", "url"),
                name="source_tenant_url_unique",
            ),
        ),
    ]
