# Generated by Django 5.2.17 on 2026-08-29 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_bot_id', models.BigIntegerField(unique=True)),
                ('owner_telegram_user_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('credential_source', models.CharField(choices=[('MANAGED', 'Managed bot'), ('MANUAL_FALLBACK', 'Fallback interno')], default='MANAGED', max_length=24)),
                ('status', models.CharField(choices=[('CONFIGURING', 'Configurando'), ('AWAITING_START', 'Aguardando /start'), ('ACTIVE', 'Conectado'), ('BLOCKED', 'Bloqueado pelo proprietario'), ('REVOKED', 'Token revogado'), ('OWNER_CHANGED', 'Proprietario alterado'), ('WEBHOOK_ERROR', 'Webhook com erro'), ('DISCONNECTED', 'Desconectado'), ('ERROR', 'Erro de configuracao')], default='CONFIGURING', max_length=24)),
                ('token_ciphertext', models.TextField(blank=True, editable=False)),
                ('token_key_version', models.PositiveSmallIntegerField(editable=False, null=True)),
                ('webhook_public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('webhook_secret_digest', models.CharField(blank=True, editable=False, max_length=64)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('access_restricted', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('token_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_bot', to='tenancy.tenant')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BotSecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=80)),
                ('context', models.CharField(blank=True, max_length=160)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_security_events', to='tenancy.tenant')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='telegram_bots.managedbot')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='BotOnboardingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_user_id', models.BigIntegerField()),
                ('suggested_name', models.CharField(max_length=64)),
                ('suggested_username', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando criacao'), ('CONFIGURING', 'Configurando'), ('AWAITING_START', 'Aguardando /start'), ('ACTIVE', 'Concluido'), ('EXPIRED', 'Expirado'), ('ABANDONED', 'Abandonado'), ('FAILED', 'Falhou')], default='PENDING', max_length=24)),
                ('is_open', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_onboarding_sessions', to='tenancy.tenant')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_sessions', to='telegram_bots.managedbot')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_open', 'expires_at'], name='telegram_bo_is_open_a61eb8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('tenant',), name='one_open_bot_onboarding_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='ManualRefreshRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_telegram_user_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluido'), ('FAILED', 'Falhou')], default='PENDING', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_refresh_requests', to='telegram_bots.managedbot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_refresh_requests', to='tenancy.tenant')),
            ],
            options={
                'ordering': ('-requested_at',),
                'indexes': [models.Index(fields=['tenant', 'requested_at'], name='telegram_bo_tenant__1440a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramUpdateReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_key', models.CharField(max_length=64)),
                ('update_id', models.BigIntegerField()),
                ('update_kind', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processando'), ('PROCESSED', 'Processado'), ('FAILED', 'Falhou'), ('REJECTED', 'Rejeitado')], default='PROCESSING', max_length=16)),
                ('outcome_code', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_receipts', to='telegram_bots.managedbot')),
            ],
            options={
                'ordering': ('-received_at',),
                'constraints': [models.UniqueConstraint(fields=('endpoint_key', 'update_id'), name='telegram_endpoint_update_unique')],
            },
        ),
    ]
