# Generated by Django 5.2.17 on 2026-08-29 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_notificationdelivery_alert_event_and_more'),
        ('telegram_bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualrefreshrequest',
            name='collection_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_refresh_requests', to='monitoring.collectionjob'),
        ),
    ]
